### ISSUE TITLE
search implementation is not possible 

### ISSUE THREAD

**Issue by kkukkadapua** [popei69/TemplateProject#10]

**Comment by popei69** [comment]
Hi there,

To add a search in the tableview, there is different ways to implement it. Either you can add the logic in the ViewModel, that will cache the data from service and set the Datasource data based on filtered content from the search. The datasource won't need to change.

The other way is to do the search treatment in the Datasource and let the ViewModel as is. It's very similar.

Here is an example for reference

```swift
struct CurrencyViewModel {
     // ...

    var rates: [CurrencyRate]
    
    // MARK: - Search bar delegate 
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        guard !searchText.isEmpty else {
            self.dataSource?.data.value.value = self.rates
            return
        }
        
        self.dataSource?.data.value = self.findRatesFor(searchText)
    }

    // ...
}
```

**Comment by kkukkadapua** [comment]
can you share full code.
